/*
 * Emma Elliott
April 3, 2020
Math Methods Program
 */

/**
 *
 * @author gregelliott
 */
public class MathMethods extends javax.swing.JFrame {

    int largest1;
    int largest2;
    int largest;
    
    int smallest1;
    int smallest2;
    int smallest;
    
    int pow1;
    int pow2;
    int pow;
    
    double side1;
    double side2;
    double side;
    
    double down1;
    double down;
    
    double up1;
    double up;
    
    int sqrt1;
    double sqrt;
    
    int radians1;
    double radians;
    /**
     * Creates new form MathMethods
     */
    public MathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        txtlargest1 = new javax.swing.JTextField();
        txtlargest2 = new javax.swing.JTextField();
        txtsmallest1 = new javax.swing.JTextField();
        txtsmallest2 = new javax.swing.JTextField();
        txtpow1 = new javax.swing.JTextField();
        txtpow2 = new javax.swing.JTextField();
        txttriangle1 = new javax.swing.JTextField();
        txttriangle2 = new javax.swing.JTextField();
        txtrounddown = new javax.swing.JTextField();
        txtroundup = new javax.swing.JTextField();
        txtsqrt = new javax.swing.JTextField();
        txttoradians = new javax.swing.JTextField();
        btnlargest = new javax.swing.JButton();
        btnsmallest = new javax.swing.JButton();
        btnpow = new javax.swing.JButton();
        btnhypotenuse = new javax.swing.JButton();
        btnrounddown = new javax.swing.JButton();
        btnroundup = new javax.swing.JButton();
        btnsqrt = new javax.swing.JButton();
        btntoradians = new javax.swing.JButton();
        lbl1B = new javax.swing.JLabel();
        lbl2B = new javax.swing.JLabel();
        lbl3B = new javax.swing.JLabel();
        lbl4B = new javax.swing.JLabel();
        lbl5B = new javax.swing.JLabel();
        lbl6B = new javax.swing.JLabel();
        lbl7B = new javax.swing.JLabel();
        lbl8B = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("Math Methods");

        lbl1.setText("Enter two numbers and click the button. The program will display the largest number.");

        lbl2.setText("Enter two numbers and click the button. The program will display the smallest number.");

        lbl3.setText("Enter two numbers and click the button. The program will display the first number to the power of the second.");

        lbl4.setText("Enter the length of two sides of a right triangle. The program will display the hypotenuse of the triangle.");

        lbl5.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer.");

        lbl6.setText("Enter an integer. The program will display the square root of the integer.");

        lbl7.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer.");

        lbl8.setText("Enter an angle in degrees. The program will display the angle in radians.");

        txtlargest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlargest1ActionPerformed(evt);
            }
        });

        txtlargest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlargest2ActionPerformed(evt);
            }
        });

        txtsmallest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsmallest1ActionPerformed(evt);
            }
        });

        txtsmallest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsmallest2ActionPerformed(evt);
            }
        });

        txtpow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpow1ActionPerformed(evt);
            }
        });

        txtpow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpow2ActionPerformed(evt);
            }
        });

        txttriangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttriangle1ActionPerformed(evt);
            }
        });

        txttriangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttriangle2ActionPerformed(evt);
            }
        });

        txtrounddown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrounddownActionPerformed(evt);
            }
        });

        txtroundup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroundupActionPerformed(evt);
            }
        });

        txtsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsqrtActionPerformed(evt);
            }
        });

        txttoradians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoradiansActionPerformed(evt);
            }
        });

        btnlargest.setText("Largest");
        btnlargest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlargestActionPerformed(evt);
            }
        });

        btnsmallest.setText("Smallest");
        btnsmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsmallestActionPerformed(evt);
            }
        });

        btnpow.setText("To the power of...");
        btnpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpowActionPerformed(evt);
            }
        });

        btnhypotenuse.setText("Hypotenuse");
        btnhypotenuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhypotenuseActionPerformed(evt);
            }
        });

        btnrounddown.setText("Round down");
        btnrounddown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrounddownActionPerformed(evt);
            }
        });

        btnroundup.setText("Round up");
        btnroundup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundupActionPerformed(evt);
            }
        });

        btnsqrt.setText("Square Root");
        btnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsqrtActionPerformed(evt);
            }
        });

        btntoradians.setText("To radians");
        btntoradians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoradiansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtroundup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnroundup)
                        .addGap(68, 68, 68)
                        .addComponent(lbl6B))
                    .addComponent(lbl5)
                    .addComponent(lbl7)
                    .addComponent(lbl6)
                    .addComponent(lbl8))
                .addGap(0, 342, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtlargest1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtlargest2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnlargest)
                        .addGap(83, 83, 83)
                        .addComponent(lbl1B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtsmallest1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtsmallest2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnsmallest)
                        .addGap(70, 70, 70)
                        .addComponent(lbl2B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtpow1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnpow)
                        .addGap(42, 42, 42)
                        .addComponent(lbl3B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txttriangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttriangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnhypotenuse)
                        .addGap(55, 55, 55)
                        .addComponent(lbl4B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtrounddown, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnrounddown)
                        .addGap(43, 43, 43)
                        .addComponent(lbl5B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnsqrt)
                        .addGap(53, 53, 53)
                        .addComponent(lbl7B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txttoradians, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btntoradians)
                        .addGap(41, 41, 41)
                        .addComponent(lbl8B)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlargest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlargest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlargest)
                    .addComponent(lbl1B))
                .addGap(1, 1, 1)
                .addComponent(lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsmallest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsmallest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsmallest)
                    .addComponent(lbl2B))
                .addGap(1, 1, 1)
                .addComponent(lbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpow)
                    .addComponent(lbl3B))
                .addGap(1, 1, 1)
                .addComponent(lbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttriangle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttriangle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhypotenuse)
                    .addComponent(lbl4B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrounddown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrounddown)
                    .addComponent(lbl5B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtroundup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnroundup)
                    .addComponent(lbl6B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsqrt)
                    .addComponent(lbl7B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttoradians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntoradians)
                    .addComponent(lbl8B))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlargest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlargest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlargest1ActionPerformed

    private void txtlargest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlargest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlargest2ActionPerformed

    private void txtsmallest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsmallest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsmallest1ActionPerformed

    private void txtsmallest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsmallest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsmallest2ActionPerformed

    private void txtpow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpow1ActionPerformed

    private void txtpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpow2ActionPerformed

    private void txttriangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttriangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttriangle1ActionPerformed

    private void txttriangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttriangle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttriangle2ActionPerformed

    private void txtrounddownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrounddownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrounddownActionPerformed

    private void txtroundupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroundupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroundupActionPerformed

    private void txtsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsqrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsqrtActionPerformed

    private void txttoradiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoradiansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoradiansActionPerformed

    private void btnlargestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlargestActionPerformed
        largest1= Integer.parseInt(txtlargest1.getText());
        largest2= Integer.parseInt(txtlargest2.getText());
        largest=(int)Math.max(largest1, largest2);
        lbl1B.setText(String.valueOf(largest));
// TODO add your handling code here:
    }//GEN-LAST:event_btnlargestActionPerformed

    private void btnsmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsmallestActionPerformed
        smallest1= Integer.parseInt(txtsmallest1.getText());
        smallest2= Integer.parseInt(txtsmallest2.getText());
        smallest=(int)Math.min(smallest1, smallest2);
        lbl2B.setText(String.valueOf(smallest));
// TODO add your handling code here:
    }//GEN-LAST:event_btnsmallestActionPerformed

    private void btnpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpowActionPerformed
        pow1= Integer.parseInt(txtpow1.getText());
        pow2= Integer.parseInt(txtpow2.getText());
        pow=(int)Math.pow(pow1, pow2);
        lbl3B.setText(String.valueOf(pow));
// TODO add your handling code here:
    }//GEN-LAST:event_btnpowActionPerformed

    private void btnhypotenuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhypotenuseActionPerformed
        side1= Integer.parseInt(txttriangle1.getText());
        side2= Integer.parseInt(txttriangle2.getText());
        side=(double)Math.hypot(side1, side2);
        lbl4B.setText(String.valueOf(side)); 
// TODO add your handling code here:
    }//GEN-LAST:event_btnhypotenuseActionPerformed

    private void btnrounddownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrounddownActionPerformed
        down1= Double.parseDouble(txtrounddown.getText());
        down=(double)Math.floor(down1);
        lbl5B.setText(String.valueOf(down));
// TODO add your handling code here:
    }//GEN-LAST:event_btnrounddownActionPerformed

    private void btnroundupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundupActionPerformed
        up1= Double.parseDouble(txtroundup.getText());
        up=(double)Math.ceil(up1);
        lbl6B.setText(String.valueOf(up));
// TODO add your handling code here:
    }//GEN-LAST:event_btnroundupActionPerformed

    private void btnsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsqrtActionPerformed
        sqrt1= Integer.parseInt(txtsqrt.getText());
        sqrt=(double)Math.sqrt(sqrt1);
        lbl7B.setText(String.valueOf(sqrt)); 
// TODO add your handling code here:
    }//GEN-LAST:event_btnsqrtActionPerformed

    private void btntoradiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoradiansActionPerformed
        radians1= Integer.parseInt(txttoradians.getText());
        radians=(double)Math.toRadians(radians1);
        lbl8B.setText(String.valueOf(radians));
// TODO add your handling code here:
    }//GEN-LAST:event_btntoradiansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhypotenuse;
    private javax.swing.JButton btnlargest;
    private javax.swing.JButton btnpow;
    private javax.swing.JButton btnrounddown;
    private javax.swing.JButton btnroundup;
    private javax.swing.JButton btnsmallest;
    private javax.swing.JButton btnsqrt;
    private javax.swing.JButton btntoradians;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl1B;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl2B;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3B;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl4B;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl5B;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl6B;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl7B;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl8B;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtlargest1;
    private javax.swing.JTextField txtlargest2;
    private javax.swing.JTextField txtpow1;
    private javax.swing.JTextField txtpow2;
    private javax.swing.JTextField txtrounddown;
    private javax.swing.JTextField txtroundup;
    private javax.swing.JTextField txtsmallest1;
    private javax.swing.JTextField txtsmallest2;
    private javax.swing.JTextField txtsqrt;
    private javax.swing.JTextField txttoradians;
    private javax.swing.JTextField txttriangle1;
    private javax.swing.JTextField txttriangle2;
    // End of variables declaration//GEN-END:variables
}
